GAMETICK = 32
LOGINSERVERDOMAIN='127.0.0.1'

DBIP='127.0.0.1'
DBUSER='DBUSER'
DBPW='DBPW'
DBNAME='DBNAME'

DEFAULT_MENE = 'uusimene'
DEFAULT_MAP="Road Two"
DEFAULT_X=9
DEFAULT_Y=9

TILE_TYPE_WALKABLE = 0
TILE_TYPE_BLOCKED  = 1
TILE_TYPE_WARP     = 2
TILE_TYPE_NPCAVOID = 4
TILE_TYPE_FIGHT = 5

MAX_LEVEL=25

CHATSPAMLIMIT = 3
CHATSPAMLIMIT_TIME = 5000 #ms
BANNEDCHATCHARS = ''
MAX_CHAT_INPUT = 80


SHOWUP_NORMAL=1
SHOWUP_UNCOMMON=2
SHOWUP_RARE=3

CHANCE_TO_ENCOUNTER=10./50 #10./185 original

PLAYER_ONE_TURN=1
PLAYER_TWO_TURN=2

ENEMY_TEAM=0
OWN_TEAM=1

ABILITY_TYPE_ATTACK=0
ABILITY_TYPE_HEAL=1

NPC_MENE_ATTACK_WAIT_TIME=800

ATTACK_RNG_MISS=0
ATTACK_RNG_NORMAL=1
ATTACK_RNG_CRIT=2

NPC_STAT_LOWER=0.85

MAX_SHIRT=2
MAX_SHOES=1
MAX_HAT=3
MAX_FACE=3

GUILD_OWNER=2
GUILD_MODERATOR=1
GUILD_MEMBER=0

NPC_WALKTYPE_STOPPED=0
NPC_WALKTYPE_RESTRICTED=1
NPC_WALKTYPE_FREEWALK=2

NPC_TALK_DELAY=1000

NPC_WALK_DELAY_LOWERLIMIT=2000
NPC_WALK_DELAY_UPPERLIMIT=10000

MAX_NPC_TALK_DISTANCE=2

DIR_DOWN = 0
DIR_LEFT = 1
DIR_RIGHT = 3
DIR_UP = 2

WALKSPEED = 640 #milliseconds

ADMIN_MODERATOR   = 1
ADMIN_ADMIN    = 2
ADMIN_CREATOR = 3

MAX_MUTE_TIME_IN_MINUTES=12*60

MAX_PARTY_SIZE=5

NPC_ACTIONTYPE_TALK=0
NPC_ACTIONTYPE_HEAL=1
NPC_ACTIONTYPE_SHOP=2

MATCH_IN_PROGRESS=1
MATCH_PLAYER_WON=2
MATCH_NPC_WON=3
MATCH_MENE_CAUGHT=4
MATCH_PLAYER_LEFT=5

MENE_INVENTORYTYPE_DEFAULT=1
MENE_INVENTORYTYPE_CARRYING=2
MENE_INVENTORYTYPE_BANK=3

